### ISSUE TITLE
Intermediate Array Problems

### ISSUE THREAD

**Issue by Abhijit2505** [LetsUpgrade/Algorithmic-Treasure#2]
You can use any programming site like Leetcode, Codeforces etc to get two questions based on array which are of **intermediate** level.
Only get two questions first. No need to get the answers or solve them for this issue.

Find two such questions on the array and post the link as a reply to this issue.

**Deadline** - 28th July 6.00PM

**Comment by AfraMP** [comment]
Question 1:
https://practice.geeksforgeeks.org/problems/find-missing-and-repeating/0
[Asked in: Amazon, Samsung]

Question 2:
https://practice.geeksforgeeks.org/problems/tic-tac-toe/0
[Asked in: Amazon, Flipkart, Microsoft ]

**Comment by AfraMP** [comment]
> You can use any programming site like Leetcode, Codeforces etc to get two questions based on array which are of **intermediate** level.
> Only get two questions first. No need to get the answers or solve them for this issue.
> 
> Find two such questions on the array and post the link as a reply to this issue.
> 
> **Deadline** - 28th July 6.00PM

Question 1:
https://practice.geeksforgeeks.org/problems/find-missing-and-repeating/0
[Asked in: Amazon, Samsung]

Question 2:
https://practice.geeksforgeeks.org/problems/tic-tac-toe/0
[Asked in: Amazon, Flipkart, Microsoft ]

**Comment by hk2608** [comment]
Question 1:
[https://practice.geeksforgeeks.org/problems/max-circular-subarray-sum/0](url)
[Asked in D-E-Shaw]
Question 2:
[https://leetcode.com/problems/trapping-rain-water/](url)
[Asked in Google,Facebook,Netflix,Apple]
