### ISSUE TITLE
Linked List problems

### ISSUE THREAD

**Issue by Abhijit2505** [LetsUpgrade/Algorithmic-Treasure#4]
You can use any programming site like Leetcode, Codeforces etc to get two questions based on Linked List.

- Only get two questions first. 

- Solve both the questions

- Upload the solution and the documentation

**Deadline - 8th August 2020**

**Comment by Abhijit2505** [comment]
Everyone Start Putting the Problems Here

**Comment by abhinavmaharana** [comment]
1) https://www.interviewbit.com/problems/k-reverse-linked-list/
 [Amazon,Google]
2) https://www.interviewbit.com/problems/reverse-alternate-k-nodes/
[Amazon,LeanApps]

**Comment by Rsr0** [comment]
Detect Loop in linked list
https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1
[Amazon, Samsung, Walmart]
Nth node from end of linked list
https://practice.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1
 [Adobe, Amazon, Samsung, Qualcomm]

**Comment by pg00019** [comment]
Question-1:
https://practice.geeksforgeeks.org/problems/delete-middle-of-linked-list/1/?track=ppc-linkedlist&batchId=221
[Amazon, FlipKart,Microsoft]
Question-2:
https://practice.geeksforgeeks.org/problems/quick-sort-on-linked-list/1/?track=ppc-linkedlist&batchId=221
[Paytm]

**Comment by pixan198** [comment]
1. https://practice.geeksforgeeks.org/problems/add-1-to-a-number-represented-as-linked-list/1
`Asked in: Amazon`


2. https://practice.geeksforgeeks.org/problems/absolute-list-sorting/1
`Asked in: Amazon, OYO`

**Comment by chaitali0210** [comment]
1. https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1
>> Asked in: Amazon,Microsoft, Paytm
2. https://practice.geeksforgeeks.org/problems/circular-linked-list/1
>> Asked in: MAQ Softwares,Microsoft, SAP Labs

**Comment by MercyRabecal** [comment]
1.https://www.interviewbit.com/problems/palindrome-list/
Asked in:Microsoft, amazon
2.https://www.interviewbit.com/problems/merge-two-sorted-lists/
Asked in :Microsoft, amazon, yahoo

**Comment by AfraMP** [comment]
Question 1 :
https://www.interviewbit.com/problems/merge-two-sorted-lists/
[Asked in : Microsoft, Amazon, Yahoo]
Question 2 : 
https://www.interviewbit.com/problems/even-reverse/
[Asked in : Amazon]

**Comment by chaitali0210** [comment]
1. https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1
>> Asked in: Amazon,Microsoft, Paytm
2. https://practice.geeksforgeeks.org/problems/circular-linked-list/1
>> Asked in: MAQ Softwares,Microsoft, SAP Labs

**Comment by Abhijit2505** [comment]
Everyone please get started with solving these problems, The questions are awesome.
Make sure you submit your code to the sites from where you are taking the question and make a PR only after getting all test cases passed.
Make a PR before Sunday. All the very best.

**Comment by ishi0301** [comment]
q1)https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1
asked in:   adobe,  Amazon, Flipkart
q2)  https://practice.geeksforgeeks.org/problems/rotate-a-linked-list/1
asked in: amazon, MakeMyTrip

**Comment by Himanshi2016** [comment]
1)
https://practice.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1
Asked in: Amazon, Adobe ,Samsung, Snapdeal , Hike, FactSet, Qualcomm, MAQ software

2)
https://practice.geeksforgeeks.org/problems/delete-middle-of-linked-list/1
Asked in: Microsoft, Flipkart, Amazon
