### ISSUE TITLE
Website Task  - 1

### ISSUE THREAD

**Issue by Abhijit2505** [LetsUpgrade/Algorithmic-Treasure#41]
Bring some templates of the documentation websites which used bootstrap and no backend.
Two things to notice while bringing the template,

**1 - It must be inside MIT license, I mean no copyright issues.
2 - It must not have any backend programming involved.**

Submission Deadline - **25th Aug 2020**

**Comment by Himanshi2016** [comment]
1. https://startbootstrap.com/previews/creative/

2. https://colorlib.com/shapely/

**Comment by MercyRabecal** [comment]
1. https://htmlstream.com/templates/stream-sketch-ui-kit

2. https://startbootstrap.com/previews/scrolling-nav/
